---
title: "extra_leaflet_and_code"
author: "RN7"
date: "November 23, 2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

A quick reminder that the formula is: $$\large\frac{(Fahrenheit - 32)\cdot5}{9} = Celsius$$
For those curious the formula is: $$\large Temperature (Celsius) + 0.5555\left(6.11e^{5417.753(\frac{1}{273.16}-\frac{1}{273.15+Dew Point})} - 10\right) $$

```{r avg. summer and winter}

library(ggplot2)
library(ggrepel)
library(xkcd)
library(extrafont)

xrange <- range(climate_japan$summer_humidex)
yrange <- range(climate_japan$winter_avg_temp)

set.seed(8)


climate_japan %>% 
  ggplot(aes(summer_avg_temp, winter_avg_temp)) +
  geom_point() +
  geom_text_repel(aes(label = City), 
                  family = "xkcd",
                  max.iter = 50000) +
  ggtitle("Where to live in Japan based on your temperature preferences!",
          subtitle = "Data from airport weather stations, 2016-2017") +
  xlab("Avg. summer temperature in Celsius") +
  ylab("Avg. winter temperature in Celsius") +
  xkcdaxis(xrange = xrange,
           yrange = yrange) +
  theme_xkcd() +
  theme(text = element_text(size = 16, family = "xkcd")) +
  annotate("text", x = 15, y = 0, label = "Hokkaido Island", family = "xkcd", size = 6) +
  annotate("segment", y = 2, yend = -5.5, x = 18.7, xend = 20.6, color = "blue", size = 1.5) +
  annotate("segment", y = -3, yend = -5.5, x = 14.5, xend = 16.5, color = "blue", size = 1.5) +
  annotate("text", x = 25, y = 20, label = "Okinawa and \nRyukyu Islands", family = "xkcd", size = 5) +
  annotate("segment", y = 17.5, yend = 15, x = 26, xend = 29.5, color = "darkred", size = 1.5) +
  annotate("segment", y = 22, yend = 22, x = 27, xend = 30.5, color = "darkred", size = 1.5) +
  annotate("text", x = 18.5, y = 10, label = "Honshu, Kyushu, \n and Shikoku Islands", family = "xkcd", size = 5.5)

```





Now for the Okinawa and Ryukyu Islands:

```{r Okinawa-Ryukyu-map}

climate_japan_map %>% 
  filter(lat < 30) %>% 
  ggplot(aes(lon, lat)) +
  geom_point(aes(color = winter_avg_temp), size = 3.5) +
  geom_text_repel(aes(label = City),
                  family = "xkcd", size = 4.5,
                  max.iter = 50000) +
  geom_polygon(data = JPN %>% filter(lat < 30 & long < 133), aes(x = long, y = lat, group = group), 
               fill = NA, color = "black") +
  coord_map() +
  labs(title = "Avg. Winter Temperature in Okinawa and Ryukyu Islands",
       subtitle = "Data from Iowa Environment Mesonet 2016-2017",
       x = "", y = "") +
  theme_xkcd() +
  theme(text = element_text(family = "xkcd", size = 14)) +
  scale_color_gradient(low = "#08306B")

climate_japan_map %>% 
  filter(lat < 30) %>% 
  ggplot(aes(lon, lat)) +
  geom_point(aes(color = summer_humidex), size = 3.5) +
  geom_text_repel(aes(label = City),
                  family = "xkcd", size = 4.5,
                  max.iter = 50000) +
  geom_polygon(data = JPN %>% filter(lat < 30 & long < 133), aes(x = long, y = lat, group = group), 
               fill = NA, color = "black") +
  coord_map() +
  labs(title = "Summer Humidex in Okinawa and Ryukyu Islands",
       subtitle = "Data from Iowa Environment Mesonet 2016-2017",
       x = "", y = "") +
  theme_xkcd() +
  theme(text = element_text(family = "xkcd", size = 14)) +
  scale_color_gradient(low = "#FCBBA1", high = "#67000D")

```







```{r, xkcd-graph, fig.height=7, fig.width=8, fig.align='center'}
library(tidyverse)
library(ggforce)

climate_japan <- readRDS("data/climate_japan.RDS")

desc_hot <- "HOT HOT HOT"
desc_norm <- "balanced??"
desc_cold <- "brrrr COLD!"

climate_japan %>% 
  ggplot(aes(summer_humidex, winter_avg_temp)) +
  geom_mark_ellipse(aes(filter = summer_humidex > 37 & winter_avg_temp > 15,
                        label = "Okinawa/Ryukyu Region", description = desc_hot),
                    color = "red", con.colour = "red", label.colour = "red") +
  geom_mark_ellipse(aes(filter = summer_humidex > 27 & summer_humidex < 39 &
                          winter_avg_temp > 0 & winter_avg_temp < 11.5,
                        label = "Honshu/Shikoku/Kyushu Region", description = desc_norm)) +
  geom_mark_ellipse(aes(filter = summer_humidex < 26 & winter_avg_temp < 0,
                        label = "Hokkaido Region", description = desc_cold),
                    color = "blue", con.colour = "blue", label.colour = "blue") +
  geom_text_repel(aes(label = City), size = 3,
                  family = "Roboto Condensed",
                  max.iter = 50000) +
  geom_point() +
  #scale_y_continuous(labels = scales::)
  ggtitle("Where to live in Japan based on your temperature preferences",
          subtitle = "Data from airport weather stations 2016-2017") +
  labs(x = "Humidex: summer heat and humidity",
       y = "Avg. winter temperature in Celsius",
       caption = "NOTE: Some airports may be far from city center") +
  theme_minimal() +
  theme(text = element_text("Roboto Condensed"),
        plot.title = element_text(size = 16))
```






```{r xkcd-graph, fig.height=7, fig.width=8, fig.align='center'}
library(ggplot2)
library(ggrepel)
library(extrafont)
set.seed(8)

climate_japan %>% 
  ggplot(aes(summer_humidex, winter_avg_temp)) +
  geom_point() +
  geom_text_repel(aes(label = City), size = 4,
                  family = "Roboto Condensed",
                  max.iter = 50000) +
  ggtitle("Where to live in Japan based on your temperature preferences",
          subtitle = "Data from airport weather stations 2016-2017") +
  xlab("Humidex: summer heat and humidity") +
  ylab("Avg. winter temperature in Celsius") +
  theme_minimal() +
  theme(text = element_text(family = "Roboto Condensed")) +
  annotate("text", x = 22, y = 1.25, label = "Hokkaido Island", 
           family = "Roboto Condensed", size = 5) +
  annotate("segment", y = 1.25, yend = -5.5, x = 26.5, xend = 29.5, 
           color = "blue", size = 1.5) +
  annotate("segment", y = -4.25, yend = -6.5, x = 19.75, xend = 21.5, 
           color = "blue", size = 1.5) +
  annotate("text", x = 35, y = 20, label = "Okinawa and \nRyukyu Islands", 
           family = "Roboto Condensed", size = 5) +
  annotate("segment", y = 15.5, yend = 14, x = 38, xend = 41, 
           color = "red", size = 1.5) +
  annotate("segment", y = 22, yend = 22, x = 40, xend = 44.5, 
           color = "red", size = 1.5) +
  annotate("text", x = 23.5, y = 10, label = "Honshu, Kyushu, \n and Shikoku Islands",
           family = "Roboto Condensed", size = 5.5)
```



```{r include=FALSE}
# Leaflet ####

# Tourist areas:

tour <- data_frame(
  location = c("Hokkaido", "Tohoku", "Tokyo", "Osaka", 
               "Kobe", "Shikoku", "Hiroshima", "Kyushu", "Okinawa"),
  City = c("Sapporo", "Aomori", "Tokyo", "Osaka", "Kobe", 
           "Kochi", "Hiroshima", "Matsuyama", "Naha")
)

tour <- left_join(tour, climate_japan_map, by = "City")

# Not have Kanazawa, Kyoto, and Nara >>> just have to manually add in i guess?
# Use the `geocode()` function from `ggmap` package to grab the longitude and latitude data.
# won't let me do all 3 at once...

library(ggmap)

Kanazawa <- ggmap::geocode("Kanazawa", output = "latlon")
Kyoto <- ggmap::geocode("Kyoto", output = "latlon")
Nara <- ggmap::geocode("Nara", output = "latlon")

missing_tour <- rbind(Kanazawa, Kyoto, Nara)

missing_tour <- missing_tour %>% mutate(City = c("Kanazawa", "Kyoto", "Nara"),
                                        location = c("Chubu", "Kyoto", "Nara"))

missing_tour

tour <- full_join(missing_tour, tour)

# not have to run geocode each time:
write.csv(tour, "~/R_materials/japan_weather_xkcd/tour.csv")

tour <- read.csv("tour.csv", stringsAsFactors = FALSE)

glimpse(tour)

websites <- data.frame(location = c("Hokkaido", "Tohoku", "Tokyo", "Osaka", "Kobe", "Shikoku", 
                        "Hiroshima", "Kyushu", "Okinawa", "Chubu", "Kyoto"),
           tour_website = c("https://www.seejapan.co.uk/where-to-go/explore-regions/destination/hokkaido",
                            "https://www.seejapan.co.uk/where-to-go/explore-regions/destination/tohoku",
                            "https://www.seejapan.co.uk/where-to-go/explore-regions/destination/tokyo",
                            "https://www.seejapan.co.uk/where-to-go/explore-regions/destination/osaka",
                            "https://www.seejapan.co.uk/where-to-go/explore-regions/destination/kobe",
                            "https://www.seejapan.co.uk/where-to-go/explore-regions/destination/shikoku",
                            "https://www.seejapan.co.uk/where-to-go/explore-regions/destination/hiroshima",
                            "https://www.seejapan.co.uk/where-to-go/explore-regions/destination/kyushu",
                            "https://www.seejapan.co.uk/where-to-go/explore-regions/destination/okinawa",
                            "https://www.seejapan.co.uk/where-to-go/explore-regions/destination/chubu",
                            "https://www.seejapan.co.uk/where-to-go/explore-regions/destination/kyoto"
                            ))

glimpse(websites)

tour <- left_join(websites, tour, by = "location")

glimpse(tour)

```


```{r leaflet map}
library(leaflet)

leaflet(tour) %>% 
  addTiles() %>% 
  setView(lng = 137.7, lat = 36.5, zoom = 7) %>% 
  addCircles(lng = ~lon, lat = ~lat, radius = 5000, color = "darkred") %>% 
  addMarkers(lng = ~lon, lat = ~lat, 
             label = paste(
               tour$City,
               "|",
               "Winter Avg.(Celsius):", round(tour$winter_avg_temp, 2), 
               "|",
               "Summer Humidex:", round(tour$summer_humidex, 2)),
             popup = ~tour_website,
             labelOptions = labelOptions(textsize = "12px")
             )

```
